apiVersion: v1
kind: ConfigMap
metadata:
  name: mc3-nginx-conf
data:
  tokens.conf: |-
    server_tokens off;

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-prod
  labels:
    app: mynginx
    tier: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mynginx
      tier: production
  template:
    metadata:
      labels:
        app: mynginx
        tier: production
    spec:
      volumes:
      - name: html
        emptyDir: {}
      - name: config
        configMap:
          name: mc3-nginx-conf
      containers:
      - name: nginx
        image: aivpl/k8s-training:latest
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
        - name: config
          mountPath: /etc/nginx/conf.d/tokens.conf
          subPath: tokens.conf
        ports:
        - containerPort: 80
      - name: os
        image: ubuntu
        volumeMounts:
        - name: html
          mountPath: /html
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do date >> /html/index.html; sleep 5; done;" ]
